# Generated by Django 3.2.5 on 2021-07-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210719_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='escudo',
        ),
    ]
