# Generated by Django 3.2.5 on 2021-07-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_time_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeA', models.CharField(max_length=10, verbose_name='timeA')),
                ('timeB', models.CharField(max_length=10, verbose_name='timeB')),
                ('placar', models.CharField(max_length=10, verbose_name='placar')),
                ('rodada', models.CharField(max_length=20, verbose_name='rodada')),
                ('Serie', models.CharField(max_length=5, verbose_name='serie')),
            ],
        ),
    ]
